$pdf_mode = 1;
$pdflatex = 'xelatex -interaction=nonstopmode -file-line-error -synctex=1 %O %S';
$bibtex = 'biber %O %S';
$out_dir = 'build';
$aux_dir = 'build';
$max_repeat = 5;
$cleanup_includes_cusdep_generated = 1;
