$pdf_mode = 1;
$pdflatex = 'xelatex -interaction=nonstopmode -file-line-error -synctex=1 %O %S';
$biber = 'biber --input-directory=. %O %S';
$bibtex_use = 2;
$out_dir = 'build';
$aux_dir = 'build';
$max_repeat = 5;
$cleanup_includes_cusdep_generated = 1;
